models=[  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Badlands",
    "msrp": 47385,
    "invoice": 45727,
    "used_new_price": 47385,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "17 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Badlands",
    "msrp": 45095,
    "invoice": 43517,
    "used_new_price": 45095,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "17 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Base",
    "msrp": 32295,
    "invoice": 31811,
    "used_new_price": 32295,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Base w/Advanced 4x4",
    "msrp": 33090,
    "invoice": 32594,
    "used_new_price": 33090,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Base",
    "msrp": 36445,
    "invoice": 35898,
    "used_new_price": 36445,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Base w/Advanced 4x4",
    "msrp": 37240,
    "invoice": 36682,
    "used_new_price": 37240,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "18 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Big Bend",
    "msrp": 36285,
    "invoice": 35378,
    "used_new_price": 36285,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Big Bend w/Advanced 4x4",
    "msrp": 37080,
    "invoice": 36153,
    "used_new_price": 37080,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Big Bend w/Advanced 4x4",
    "msrp": 39070,
    "invoice": 38093,
    "used_new_price": 39070,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Big Bend",
    "msrp": 38275,
    "invoice": 37319,
    "used_new_price": 38275,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Black Diamond w/Advanced 4x4",
    "msrp": 41735,
    "invoice": 40275,
    "used_new_price": 41735,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "19 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Black Diamond w/Advanced 4x4",
    "msrp": 39745,
    "invoice": 38354,
    "used_new_price": 39745,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "19 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Black Diamond",
    "msrp": 38950,
    "invoice": 37587,
    "used_new_price": 38950,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "19 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Black Diamond",
    "msrp": 40940,
    "invoice": 39507,
    "used_new_price": 40940,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "19 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Everglades",
    "msrp": 53895,
    "invoice": 52009,
    "used_new_price": 53895,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Heritage Edition",
    "msrp": 46295,
    "invoice": 45138,
    "used_new_price": 46295,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "manual",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Heritage Limited Edition",
    "msrp": 69185,
    "invoice": 66764,
    "used_new_price": 69185,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "330 hp @ 5250 rpm",
    "torque": "415 ft-lbs. @ 3100 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Heritage Limited Edition",
    "msrp": 66895,
    "invoice": 64554,
    "used_new_price": 66895,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "330 hp @ 5250 rpm",
    "torque": "415 ft-lbs. @ 3100 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Outer Banks",
    "msrp": 44445,
    "invoice": 42890,
    "used_new_price": 44445,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Outer Banks",
    "msrp": 41855,
    "invoice": 40390,
    "used_new_price": 41855,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Outer Banks w/Advanced 4x4",
    "msrp": 46035,
    "invoice": 44424,
    "used_new_price": 46035,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Outer Banks w/Advanced 4x4",
    "msrp": 43445,
    "invoice": 41925,
    "used_new_price": 43445,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5700 rpm",
    "torque": "325 ft-lbs. @ 3400 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Raptor",
    "msrp": 73780,
    "invoice": 71198,
    "used_new_price": 73780,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "",
    "torque": "",
    "highway_fuel_economy": "16 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Wildtrak",
    "msrp": 54320,
    "invoice": 52418,
    "used_new_price": 54320,
    "body_size": "Midsize",
    "body_style": "Convertible SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "330 hp @ 5250 rpm",
    "torque": "415 ft-lbs. @ 3100 rpm",
    "highway_fuel_economy": "17 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "year": 2023,
    "trim": "Wildtrak",
    "msrp": 52780,
    "invoice": 50933,
    "used_new_price": 52780,
    "body_size": "Compact",
    "body_style": "Convertible SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "330 hp @ 5250 rpm",
    "torque": "415 ft-lbs. @ 3100 rpm",
    "highway_fuel_economy": "17 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco Sport",
    "year": 2023,
    "trim": "Badlands",
    "msrp": 36590,
    "invoice": 35310,
    "used_new_price": 36590,
    "body_size": "Compact",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "277 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco Sport",
    "year": 2023,
    "trim": "Base",
    "msrp": 29215,
    "invoice": 28776,
    "used_new_price": 29215,
    "body_size": "Compact",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco Sport",
    "year": 2023,
    "trim": "Big Bend",
    "msrp": 30930,
    "invoice": 30157,
    "used_new_price": 30930,
    "body_size": "Compact",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco Sport",
    "year": 2023,
    "trim": "Heritage",
    "msrp": 32650,
    "invoice": 31834,
    "used_new_price": 32650,
    "body_size": "Compact",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco Sport",
    "year": 2023,
    "trim": "Heritage Limited",
    "msrp": 44655,
    "invoice": 43092,
    "used_new_price": 44655,
    "body_size": "Compact",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "277 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Bronco Sport",
    "year": 2023,
    "trim": "Outer Banks",
    "msrp": 34865,
    "invoice": 33644,
    "used_new_price": 34865,
    "body_size": "Compact",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "E-Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB",
    "msrp": 57810,
    "invoice": 57810,
    "used_new_price": 57810,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "E-Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB",
    "msrp": 58970,
    "invoice": 58970,
    "used_new_price": 58970,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "E-Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/148\" WB",
    "msrp": 55000,
    "invoice": 55000,
    "used_new_price": 55000,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "E-Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/130\" WB",
    "msrp": 53790,
    "invoice": 53790,
    "used_new_price": 53790,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "E-Transit Cargo Van",
    "year": 2023,
    "trim": "350 Medium Roof w/130\" WB",
    "msrp": 54555,
    "invoice": 54555,
    "used_new_price": 54555,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "E-Transit Cargo Van",
    "year": 2023,
    "trim": "350 Medium Roof w/148\" WB",
    "msrp": 55770,
    "invoice": 55770,
    "used_new_price": 55770,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Edge",
    "year": 2023,
    "trim": "SE",
    "msrp": 37945,
    "invoice": 36807,
    "used_new_price": 37945,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "280 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Edge",
    "year": 2023,
    "trim": "SEL",
    "msrp": 39345,
    "invoice": 37771,
    "used_new_price": 39345,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "280 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Edge",
    "year": 2023,
    "trim": "ST",
    "msrp": 46485,
    "invoice": 44626,
    "used_new_price": 46485,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "335 hp @ 5550 rpm",
    "torque": "380 ft-lbs. @ 3250 rpm",
    "highway_fuel_economy": "25 mpg"
  },
  {
    "make": "Ford",
    "model": "Edge",
    "year": 2023,
    "trim": "ST-Line",
    "msrp": 43100,
    "invoice": 41376,
    "used_new_price": 43100,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "280 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Edge",
    "year": 2023,
    "trim": "Titanium",
    "msrp": 43100,
    "invoice": 41376,
    "used_new_price": 43100,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "280 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Active",
    "msrp": 30715,
    "invoice": 29486,
    "used_new_price": 30715,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Active",
    "msrp": 28845,
    "invoice": 27691,
    "used_new_price": 28845,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "FWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Base",
    "msrp": 27500,
    "invoice": 26675,
    "used_new_price": 27500,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "FWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Base",
    "msrp": 29000,
    "invoice": 28130,
    "used_new_price": 29000,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 35965,
    "invoice": 34526,
    "used_new_price": 35965,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "FWD",
    "transmission": "automatic",
    "horsepower": "165 hp @ 6250 rpm",
    "torque": "155 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 37465,
    "invoice": 35966,
    "used_new_price": 37465,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "165 hp @ 6250 rpm",
    "torque": "155 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 37465,
    "invoice": 35966,
    "used_new_price": 37465,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "280 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "Plug-In Hybrid",
    "msrp": 38500,
    "invoice": 36960,
    "used_new_price": 38500,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "FWD",
    "transmission": "automatic",
    "horsepower": "221 hp @ 6250 rpm",
    "torque": "155 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "93 mpg"
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "ST-Line",
    "msrp": 32340,
    "invoice": 31047,
    "used_new_price": 32340,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "FWD",
    "transmission": "automatic",
    "horsepower": "165 hp @ 6250 rpm",
    "torque": "155 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "ST-Line",
    "msrp": 29840,
    "invoice": 28647,
    "used_new_price": 29840,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "FWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "ST-Line",
    "msrp": 31710,
    "invoice": 30441,
    "used_new_price": 31710,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I3",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "181 hp @ 6000 rpm",
    "torque": "190 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "ST-Line Elite",
    "msrp": 38460,
    "invoice": 36921,
    "used_new_price": 38460,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "165 hp @ 6250 rpm",
    "torque": "155 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "ST-Line Elite",
    "msrp": 38460,
    "invoice": 36921,
    "used_new_price": 38460,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "280 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "ST-Line Select",
    "msrp": 34040,
    "invoice": 32679,
    "used_new_price": 34040,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "250 hp @ 5500 rpm",
    "torque": "280 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Escape",
    "year": 2023,
    "trim": "ST-Line Select",
    "msrp": 34040,
    "invoice": 32679,
    "used_new_price": 34040,
    "body_size": "Midsize",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "165 hp @ 6250 rpm",
    "torque": "155 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 77170,
    "invoice": 74083,
    "used_new_price": 77170,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 80220,
    "invoice": 77011,
    "used_new_price": 80220,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "Limited",
    "msrp": 67115,
    "invoice": 64430,
    "used_new_price": 67115,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "Limited",
    "msrp": 70165,
    "invoice": 67358,
    "used_new_price": 70165,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX King Ranch",
    "msrp": 79170,
    "invoice": 76003,
    "used_new_price": 79170,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX King Ranch",
    "msrp": 82220,
    "invoice": 78931,
    "used_new_price": 82220,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX Limited",
    "msrp": 72165,
    "invoice": 69278,
    "used_new_price": 72165,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX Limited",
    "msrp": 69115,
    "invoice": 66350,
    "used_new_price": 69115,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX Platinum",
    "msrp": 84670,
    "invoice": 81283,
    "used_new_price": 84670,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX XL Fleet",
    "msrp": 55905,
    "invoice": 53669,
    "used_new_price": 55905,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX XL Fleet",
    "msrp": 58955,
    "invoice": 56597,
    "used_new_price": 58955,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX XLT",
    "msrp": 59940,
    "invoice": 57543,
    "used_new_price": 59940,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "MAX XLT",
    "msrp": 62990,
    "invoice": 60471,
    "used_new_price": 62990,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 79620,
    "invoice": 76435,
    "used_new_price": 79620,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 82670,
    "invoice": 79363,
    "used_new_price": 82670,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5000 rpm",
    "torque": "480 ft-lbs. @ 5000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "Timberline",
    "msrp": 70705,
    "invoice": 67877,
    "used_new_price": 70705,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "440 hp @ 5000 rpm",
    "torque": "510 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "19 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "XL Fleet",
    "msrp": 52905,
    "invoice": 50789,
    "used_new_price": 52905,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "XL Fleet",
    "msrp": 55955,
    "invoice": 53717,
    "used_new_price": 55955,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "XL STX",
    "msrp": 53875,
    "invoice": 51700,
    "used_new_price": 53875,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "XLT",
    "msrp": 57940,
    "invoice": 55623,
    "used_new_price": 57940,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "year": 2023,
    "trim": "XLT",
    "msrp": 60990,
    "invoice": 58551,
    "used_new_price": 60990,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "380 hp @ 5000 rpm",
    "torque": "470 ft-lbs. @ 2250 rpm",
    "highway_fuel_economy": "21 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Base",
    "msrp": 36760,
    "invoice": 35657,
    "used_new_price": 36760,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Base",
    "msrp": 38760,
    "invoice": 37597,
    "used_new_price": 38760,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "27 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 56130,
    "invoice": 53885,
    "used_new_price": 56130,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5500 rpm",
    "torque": "415 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 54130,
    "invoice": 51965,
    "used_new_price": 54130,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5500 rpm",
    "torque": "415 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Limited",
    "msrp": 49070,
    "invoice": 47107,
    "used_new_price": 49070,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "27 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Limited",
    "msrp": 47070,
    "invoice": 45187,
    "used_new_price": 47070,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Limited Hybrid",
    "msrp": 52060,
    "invoice": 49977,
    "used_new_price": 52060,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "318 hp @ 6500 rpm",
    "torque": "322 ft-lbs. @ 2500 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Limited Hybrid",
    "msrp": 54060,
    "invoice": 51897,
    "used_new_price": 54060,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "318 hp @ 6500 rpm",
    "torque": "322 ft-lbs. @ 2500 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 56275,
    "invoice": 54025,
    "used_new_price": 56275,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5500 rpm",
    "torque": "415 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 54275,
    "invoice": 52105,
    "used_new_price": 54275,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5500 rpm",
    "torque": "415 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Platinum Hybrid",
    "msrp": 52875,
    "invoice": 50761,
    "used_new_price": 52875,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "318 hp @ 6500 rpm",
    "torque": "322 ft-lbs. @ 2500 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Platinum Hybrid",
    "msrp": 54875,
    "invoice": 52681,
    "used_new_price": 54875,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "318 hp @ 6500 rpm",
    "torque": "322 ft-lbs. @ 2500 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "ST",
    "msrp": 51505,
    "invoice": 49445,
    "used_new_price": 51505,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5500 rpm",
    "torque": "415 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "ST",
    "msrp": 49505,
    "invoice": 47525,
    "used_new_price": 49505,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 5500 rpm",
    "torque": "415 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "ST-Line",
    "msrp": 46005,
    "invoice": 44165,
    "used_new_price": 46005,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "ST-Line",
    "msrp": 48005,
    "invoice": 46085,
    "used_new_price": 48005,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "27 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "Timberline",
    "msrp": 48480,
    "invoice": 46541,
    "used_new_price": 48480,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "XLT",
    "msrp": 38570,
    "invoice": 37027,
    "used_new_price": 38570,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "28 mpg"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "year": 2023,
    "trim": "XLT",
    "msrp": 40570,
    "invoice": 38947,
    "used_new_price": 40570,
    "body_size": "Large",
    "body_style": "SUV",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "300 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3500 rpm",
    "highway_fuel_economy": "27 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 67100,
    "invoice": 62739,
    "used_new_price": 67100,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 63310,
    "invoice": 59195,
    "used_new_price": 63310,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 66805,
    "invoice": 62463,
    "used_new_price": 66805,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "King Ranch",
    "msrp": 63005,
    "invoice": 58910,
    "used_new_price": 63005,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 61270,
    "invoice": 57287,
    "used_new_price": 61270,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "325 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 57730,
    "invoice": 53978,
    "used_new_price": 57730,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "325 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 62995,
    "invoice": 58900,
    "used_new_price": 62995,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 57480,
    "invoice": 53744,
    "used_new_price": 57480,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "325 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Limited",
    "msrp": 84910,
    "invoice": 79391,
    "used_new_price": 84910,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "430 hp @ 6000 rpm",
    "torque": "570 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "23 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 68490,
    "invoice": 64038,
    "used_new_price": 68490,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 64695,
    "invoice": 60490,
    "used_new_price": 64695,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 65000,
    "invoice": 60775,
    "used_new_price": 65000,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 68795,
    "invoice": 64323,
    "used_new_price": 68795,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Raptor",
    "msrp": 76775,
    "invoice": 71785,
    "used_new_price": 76775,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "450 hp @ 5850 rpm",
    "torque": "510 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "18 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Raptor R",
    "msrp": 107350,
    "invoice": 99609,
    "used_new_price": 107350,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Supercharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "700 hp @ 6650 rpm",
    "torque": "640 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "Tremor",
    "msrp": 61110,
    "invoice": 57138,
    "used_new_price": 61110,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 39600,
    "invoice": 37818,
    "used_new_price": 39600,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 45410,
    "invoice": 43366,
    "used_new_price": 45410,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 41530,
    "invoice": 39662,
    "used_new_price": 41530,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 48225,
    "invoice": 46055,
    "used_new_price": 48225,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 42930,
    "invoice": 40999,
    "used_new_price": 42930,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "325 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 42995,
    "invoice": 41060,
    "used_new_price": 42995,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 34885,
    "invoice": 33315,
    "used_new_price": 34885,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 39195,
    "invoice": 37431,
    "used_new_price": 39195,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 40590,
    "invoice": 38764,
    "used_new_price": 40590,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "325 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 45810,
    "invoice": 43748,
    "used_new_price": 45810,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 39900,
    "invoice": 38105,
    "used_new_price": 39900,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XL",
    "msrp": 34585,
    "invoice": 33029,
    "used_new_price": 34585,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 53045,
    "invoice": 49597,
    "used_new_price": 53045,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 47800,
    "invoice": 44693,
    "used_new_price": 47800,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 50220,
    "invoice": 46955,
    "used_new_price": 50220,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 46360,
    "invoice": 43346,
    "used_new_price": 46360,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 47750,
    "invoice": 44646,
    "used_new_price": 47750,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "325 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 44550,
    "invoice": 41654,
    "used_new_price": 44550,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 50620,
    "invoice": 47329,
    "used_new_price": 50620,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V8",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "400 hp @ 6000 rpm",
    "torque": "410 ft-lbs. @ 4250 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 44855,
    "invoice": 41939,
    "used_new_price": 44855,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "22 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 41055,
    "invoice": 38386,
    "used_new_price": 41055,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 44000,
    "invoice": 41140,
    "used_new_price": 44000,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 45400,
    "invoice": 42449,
    "used_new_price": 45400,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "325 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "year": 2023,
    "trim": "XLT",
    "msrp": 40760,
    "invoice": 38110,
    "used_new_price": 40760,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "290 hp @ 6500 rpm",
    "torque": "265 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150 Lightning",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 74474,
    "invoice": 74474,
    "used_new_price": 74474,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "426 hp @ 0 rpm",
    "torque": "775 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "61 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150 Lightning",
    "year": 2023,
    "trim": "Platinum",
    "msrp": 96874,
    "invoice": 96874,
    "used_new_price": 96874,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "563 hp @ 0 rpm",
    "torque": "775 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "60 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150 Lightning",
    "year": 2023,
    "trim": "Pro",
    "msrp": 46974,
    "invoice": 46974,
    "used_new_price": 46974,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "426 hp @ 0 rpm",
    "torque": "775 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "61 mpg"
  },
  {
    "make": "Ford",
    "model": "F-150 Lightning",
    "year": 2023,
    "trim": "XLT",
    "msrp": 59474,
    "invoice": 59474,
    "used_new_price": 59474,
    "body_size": "Large",
    "body_style": "Pickup Truck",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "426 hp @ 0 rpm",
    "torque": "775 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "61 mpg"
  },
  {
    "make": "Ford",
    "model": "Mustang Mach-E",
    "year": 2023,
    "trim": "California Route 1 w/Extended Range",
    "msrp": 63575,
    "invoice": 63575,
    "used_new_price": 63575,
    "body_size": "Midsize",
    "body_style": "Hatchback",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "346 hp @ 0 rpm",
    "torque": "428 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "91 mpg"
  },
  {
    "make": "Ford",
    "model": "Mustang Mach-E",
    "year": 2023,
    "trim": "GT w/Extended Range",
    "msrp": 69895,
    "invoice": 69895,
    "used_new_price": 69895,
    "body_size": "Midsize",
    "body_style": "Hatchback",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "480 hp @ 0 rpm",
    "torque": "600 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "77 mpg"
  },
  {
    "make": "Ford",
    "model": "Mustang Mach-E",
    "year": 2023,
    "trim": "Premium w/Standard Range",
    "msrp": 54975,
    "invoice": 54975,
    "used_new_price": 54975,
    "body_size": "Midsize",
    "body_style": "Hatchback",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "96 mpg"
  },
  {
    "make": "Ford",
    "model": "Mustang Mach-E",
    "year": 2023,
    "trim": "Premium w/Standard Range",
    "msrp": 57675,
    "invoice": 57675,
    "used_new_price": 57675,
    "body_size": "Midsize",
    "body_style": "Hatchback",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "428 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "86 mpg"
  },
  {
    "make": "Ford",
    "model": "Mustang Mach-E",
    "year": 2023,
    "trim": "Select w/Standard Range",
    "msrp": 46895,
    "invoice": 46895,
    "used_new_price": 46895,
    "body_size": "Midsize",
    "body_style": "Hatchback",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "317 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "96 mpg"
  },
  {
    "make": "Ford",
    "model": "Mustang Mach-E",
    "year": 2023,
    "trim": "Select w/Standard Range",
    "msrp": 49595,
    "invoice": 49595,
    "used_new_price": 49595,
    "body_size": "Midsize",
    "body_style": "Hatchback",
    "cylinders": "",
    "engine_aspiration": "Electric Motor",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "266 hp @ 0 rpm",
    "torque": "428 ft-lbs. @ 0 rpm",
    "highway_fuel_economy": "86 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 36460,
    "invoice": 35001,
    "used_new_price": 36460,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 39945,
    "invoice": 38347,
    "used_new_price": 39945,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 34500,
    "invoice": 33120,
    "used_new_price": 34500,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "Lariat",
    "msrp": 37985,
    "invoice": 36466,
    "used_new_price": 37985,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XL",
    "msrp": 26400,
    "invoice": 25608,
    "used_new_price": 26400,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XL",
    "msrp": 30045,
    "invoice": 29144,
    "used_new_price": 30045,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XL",
    "msrp": 28585,
    "invoice": 27728,
    "used_new_price": 28585,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XL",
    "msrp": 32230,
    "invoice": 31264,
    "used_new_price": 32230,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XLT",
    "msrp": 32420,
    "invoice": 31123,
    "used_new_price": 32420,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XLT",
    "msrp": 35905,
    "invoice": 34469,
    "used_new_price": 35905,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XLT",
    "msrp": 30460,
    "invoice": 29241,
    "used_new_price": 30460,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "26 mpg"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "year": 2023,
    "trim": "XLT",
    "msrp": 33945,
    "invoice": 32587,
    "used_new_price": 33945,
    "body_size": "Compact",
    "body_style": "Pickup Truck",
    "cylinders": "I4",
    "engine_aspiration": "Turbocharged",
    "drivetrain": "4WD",
    "transmission": "automatic",
    "horsepower": "270 hp @ 5500 rpm",
    "torque": "310 ft-lbs. @ 3000 rpm",
    "highway_fuel_economy": "24 mpg"
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "150 Low Roof w/148\" WB",
    "msrp": 43230,
    "invoice": 41069,
    "used_new_price": 43230,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "150 Low Roof w/130\" WB",
    "msrp": 41955,
    "invoice": 39857,
    "used_new_price": 41955,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "150 Low Roof w/148\" WB",
    "msrp": 47925,
    "invoice": 45529,
    "used_new_price": 47925,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "150 Low Roof w/130\" WB",
    "msrp": 46650,
    "invoice": 44318,
    "used_new_price": 46650,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "150 Medium Roof w/130\" WB",
    "msrp": 47475,
    "invoice": 45102,
    "used_new_price": 47475,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "150 Medium Roof w/148\" WB",
    "msrp": 48745,
    "invoice": 46308,
    "used_new_price": 48745,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "150 Medium Roof w/148\" WB",
    "msrp": 44055,
    "invoice": 41852,
    "used_new_price": 44055,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 High Roof w/148\" WB",
    "msrp": 51845,
    "invoice": 49253,
    "used_new_price": 51845,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 High Roof w/148\" WB",
    "msrp": 47155,
    "invoice": 44797,
    "used_new_price": 47155,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 High Roof w/148\" WB",
    "msrp": 53070,
    "invoice": 50416,
    "used_new_price": 53070,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 High Roof w/148\" WB",
    "msrp": 48375,
    "invoice": 45957,
    "used_new_price": 48375,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Low Roof w/148\" WB",
    "msrp": 48875,
    "invoice": 46432,
    "used_new_price": 48875,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Low Roof w/148\" WB",
    "msrp": 44175,
    "invoice": 41967,
    "used_new_price": 44175,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Low Roof w/130\" WB",
    "msrp": 47600,
    "invoice": 45220,
    "used_new_price": 47600,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Low Roof w/130\" WB",
    "msrp": 42905,
    "invoice": 40760,
    "used_new_price": 42905,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Medium Roof w/130\" WB",
    "msrp": 48425,
    "invoice": 46004,
    "used_new_price": 48425,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Medium Roof w/130\" WB",
    "msrp": 43730,
    "invoice": 41544,
    "used_new_price": 43730,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Medium Roof w/148\" WB",
    "msrp": 45005,
    "invoice": 42755,
    "used_new_price": 45005,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "250 Medium Roof w/148\" WB",
    "msrp": 49700,
    "invoice": 47215,
    "used_new_price": 49700,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 HD High Roof w/148\" WB, 9,950 lbs. GVWR",
    "msrp": 55305,
    "invoice": 52540,
    "used_new_price": 55305,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 HD High Roof w/148\" WB, 10,360 lbs. GVWR",
    "msrp": 50570,
    "invoice": 48041,
    "used_new_price": 50570,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 HD High Roof w/148\" WB, 10,360 lbs. GVWR",
    "msrp": 57115,
    "invoice": 54259,
    "used_new_price": 57115,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "310 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 2500 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 HD High Roof w/148\" WB, 11,000 lbs. GVWR",
    "msrp": 52575,
    "invoice": 49947,
    "used_new_price": 52575,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "310 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 2500 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 HD High Roof w/148\" WB, 11,000 lbs. GVWR",
    "msrp": 58160,
    "invoice": 55252,
    "used_new_price": 58160,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Twin-Turbo",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "310 hp @ 5000 rpm",
    "torque": "400 ft-lbs. @ 2500 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB",
    "msrp": 48405,
    "invoice": 45985,
    "used_new_price": 48405,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB",
    "msrp": 53100,
    "invoice": 50445,
    "used_new_price": 53100,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB",
    "msrp": 54320,
    "invoice": 51604,
    "used_new_price": 54320,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB",
    "msrp": 49625,
    "invoice": 47144,
    "used_new_price": 49625,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB, 9,950 lbs. GVWR",
    "msrp": 48945,
    "invoice": 46498,
    "used_new_price": 48945,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB, 9,950 lbs. GVWR",
    "msrp": 53640,
    "invoice": 50958,
    "used_new_price": 53640,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB, 9,950 lbs. GVWR",
    "msrp": 54860,
    "invoice": 52117,
    "used_new_price": 54860,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 High Roof w/148\" WB, 9,950 lbs. GVWR",
    "msrp": 50165,
    "invoice": 47656,
    "used_new_price": 50165,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/130\" WB",
    "msrp": 48850,
    "invoice": 46408,
    "used_new_price": 48850,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/148\" WB",
    "msrp": 50125,
    "invoice": 47619,
    "used_new_price": 50125,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/148\" WB",
    "msrp": 45430,
    "invoice": 43159,
    "used_new_price": 45430,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/130\" WB",
    "msrp": 44155,
    "invoice": 41947,
    "used_new_price": 44155,
    "body_size": "Midsize",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/148\" WB, 9,950 lbs. GVWR",
    "msrp": 45970,
    "invoice": 43671,
    "used_new_price": 45970,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Low Roof w/148\" WB, 9,950 lbs. GVWR",
    "msrp": 50660,
    "invoice": 48127,
    "used_new_price": 50660,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Medium Roof w/130\" WB",
    "msrp": 44975,
    "invoice": 42727,
    "used_new_price": 44975,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Medium Roof w/148\" WB",
    "msrp": 50945,
    "invoice": 48398,
    "used_new_price": 50945,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "AWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  },
  {
    "make": "Ford",
    "model": "Transit Cargo Van",
    "year": 2023,
    "trim": "350 Medium Roof w/148\" WB",
    "msrp": 46255,
    "invoice": 43942,
    "used_new_price": 46255,
    "body_size": "Large",
    "body_style": "Cargo Van",
    "cylinders": "V6",
    "engine_aspiration": "Naturally Aspirated",
    "drivetrain": "RWD",
    "transmission": "automatic",
    "horsepower": "275 hp @ 6250 rpm",
    "torque": "260 ft-lbs. @ 4000 rpm",
    "highway_fuel_economy": ""
  }
]